webtalk_init -webtalk_dir D:/88-ISE_share/SIM/vivado_sim/ip_vivado.sim/sim_1/behav/xsim/xsim.dir/tb_fpga_qspi_sim_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Jul 12 18:18:06 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e2f5227c-1c59-46d6-9610-15e88e176c04" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "6f64d7b443964a58bbd73ee764f8f2bd" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "189" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2304 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "27" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "432 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "347 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "636" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "73" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "2.09_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "157400_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4179241304 -regid "" -xml D:/88-ISE_share/SIM/vivado_sim/ip_vivado.sim/sim_1/behav/xsim/xsim.dir/tb_fpga_qspi_sim_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/88-ISE_share/SIM/vivado_sim/ip_vivado.sim/sim_1/behav/xsim/xsim.dir/tb_fpga_qspi_sim_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/88-ISE_share/SIM/vivado_sim/ip_vivado.sim/sim_1/behav/xsim/xsim.dir/tb_fpga_qspi_sim_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
