# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param simulator.modelsimInstallPath C:/modeltech64_2019.2/win64
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/88-ISE_share/vivado_sim/ip_vivado.cache/wt [current_project]
set_property parent.project_path D:/88-ISE_share/vivado_sim/ip_vivado.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/88-ISE_share/vivado_sim/ip_vivado.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/88-ISE_share/spi-simulator/design_rtl/my_rtl/async_fifo/asyn_fifo_top.v
  D:/88-ISE_share/spi-simulator/design_rtl/my_rtl/cyp2sdram/cyp2sdram_top.v
  D:/88-ISE_share/spi-simulator/design_rtl/my_rtl/cyp2sdram/cyp_wr_fifo.v
  D:/88-ISE_share/spi-simulator/design_rtl/my_rtl/async_fifo/empty.v
  D:/88-ISE_share/spi-simulator/design_rtl/my_rtl/qspi2sdram/fifo_rd_sdram.v
  D:/88-ISE_share/spi-simulator/design_rtl/my_rtl/cyp2sdram/fifo_wr_sdram.v
  D:/88-ISE_share/spi-simulator/design_rtl/my_rtl/async_fifo/fifomen.v
  D:/88-ISE_share/spi-simulator/design_rtl/my_rtl/async_fifo/full.v
  D:/88-ISE_share/spi-simulator/design_rtl/my_rtl/qspi2sdram/qspi2sdram_top.v
  D:/88-ISE_share/spi-simulator/design_rtl/my_rtl/qspi2sdram/qspi_rd_fifo.v
  D:/88-ISE_share/spi-simulator/design_rtl/my_rtl/sdram_ctrl/sdram_cmd.v
  D:/88-ISE_share/spi-simulator/design_rtl/my_rtl/sdram_ctrl/sdram_core.v
  D:/88-ISE_share/spi-simulator/design_rtl/my_rtl/sdram_ctrl/sdram_data.v
  D:/88-ISE_share/spi-simulator/design_rtl/my_rtl/sdram_ctrl/sdram_t.v
  D:/88-ISE_share/spi-simulator/design_rtl/my_rtl/sdram_ctrl/sdram_top.v
  D:/88-ISE_share/spi-simulator/design_rtl/my_rtl/async_fifo/sync_r2w.v
  D:/88-ISE_share/spi-simulator/design_rtl/my_rtl/async_fifo/sync_w2r.v
  D:/88-ISE_share/spi-simulator/design_rtl/my_rtl/qspi_simulator_top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top qspi_simulator_top -part xc7k325tffg900-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef qspi_simulator_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file qspi_simulator_top_utilization_synth.rpt -pb qspi_simulator_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
